### ISSUE TITLE
Selecting all machines does not allow to deselect a specific one

### ISSUE THREAD

**Issue by skatsaounis** [canonical/maas-ui#5249] opened 2024-01-04 07:50 UTC
**Describe the bug**

The intention of a user is to select all machines but one from a list of e.g. 10. Since it is easier to select all 10 and then deselect the one not needed, user is trying to perform the action but deselect is not allowed. Then user has to deselect all to enable again the selection and select the desired 9 one by one.

**maas-ui version**

97186a9204557461cd0cf1852fc859a6dcaf8aea

**MAAS version**

commit from latest/edge: f5c5d5717e7b455d01788e07fd3f74f95b002b44

**LP issue**

N/A

**To Reproduce**

1. Go to Machines and select all
2. Try to deselect a specific one
3. All select options are disabled
4. To enable the selection, user can only deselect all

**Expected behavior**

Select options of each machine are not disabled

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 121.0

**Additional context**

N/A

**Comment by petermakowski** [comment] 2024-01-04 08:29
Thank you for reporting this @skatsaounis. We generally track maas-ui bugs on launchpad. Looks like it's a duplicate of: https://bugs.launchpad.net/maas-ui/+bug/2013167

**Comment by petermakowski** [comment] 2024-01-04 08:31
I linked this issue in the launchpad bug where we'll track progress.

**Closed by petermakowski** 2024-01-04 08:31 UTC
Labels: Bug 🐛
